#include "internal.h"
#include "c_backend_internal.h"

#include <string.h>

void c_backend_emit_prelude(FILE *output, bool native_runtime) {
    if (native_runtime)
        fputs("#include \"lang/lang.h\"\n", output);
    fputs(
        "#include <stdbool.h>\n"
        "#include <float.h>\n"
        "#include <inttypes.h>\n"
        "#include <stdint.h>\n"
        "#include <stdio.h>\n"
        "#include <stdlib.h>\n"
        "#include <string.h>\n\n"
        "typedef struct aster_str {\n"
        "    const unsigned char *data;\n"
        "    size_t length;\n"
        "} aster_str;\n"
        "typedef struct aster_string {\n"
        "    size_t references;\n"
        "    unsigned char *data;\n"
        "    size_t length;\n"
        "} aster_string;\n"
        "typedef struct aster_string_builder {\n"
        "    size_t references;\n"
        "    unsigned char *data;\n"
        "    size_t length;\n"
        "    size_t capacity;\n"
        "} aster_string_builder;\n"
        "typedef union aster_string_owner {\n"
        "    aster_string string;\n"
        "    aster_string_builder builder;\n"
        "} aster_string_owner;\n"
        "typedef struct aster_buffer {\n"
        "    unsigned char *data;\n"
        "    size_t length;\n"
        "} aster_buffer;\n"
        "typedef struct aster_arena_block aster_arena_block;\n"
        "typedef struct aster_arena {\n"
        "    aster_arena_block *blocks;\n"
        "} aster_arena;\n"
        "struct aster_arena_block {\n"
        "    aster_arena_block *next;\n"
        "    void *data;\n"
        "};\n"
        "typedef aster_string aster_url;\n"
        "typedef struct aster_html aster_html;\n"
        "typedef struct aster_html_storage aster_html_storage;\n"
        "typedef struct aster_html_style_occurrence {\n"
        "    aster_str id;\n"
        "    size_t start;\n"
        "    size_t end;\n"
        "} aster_html_style_occurrence;\n"
        "struct aster_html {\n"
        "    aster_html_storage *storage;\n"
        "    const unsigned char *tag;\n"
        "    size_t tag_length;\n"
        "    bool open;\n"
        "    bool attached;\n"
        "    bool suppressed;\n"
        "    size_t start;\n"
        "    aster_str static_style_id;\n"
        "};\n"
        "struct aster_html_storage {\n"
        "    unsigned char *data;\n"
        "    size_t length;\n"
        "    size_t capacity;\n"
        "    aster_html children[32];\n"
        "    size_t child_count;\n"
        "    aster_str *style_ids;\n"
        "    size_t style_id_count;\n"
        "    size_t style_id_capacity;\n"
        "    aster_html_style_occurrence *style_occurrences;\n"
        "    size_t style_occurrence_count;\n"
        "    size_t style_occurrence_capacity;\n"
        "};\n"
        "typedef union aster_html_owner {\n"
        "    aster_html html;\n"
        "    aster_string string;\n"
        "} aster_html_owner;\n"
        "typedef aster_html aster_element_builder;\n\n"
        "typedef struct aster_task aster_task;\n\n"
        "aster_string *aster_string_from(aster_str value);\n"
        "aster_string *aster_string_clone(const aster_string *value);\n"
        "void aster_string_drop(aster_string *value);\n"
        "aster_str aster_string_as_str(const aster_string *value);\n"
        "aster_string_builder *aster_builder_new(void);\n"
        "aster_string_builder *aster_builder_with_capacity(\n"
        "        size_t capacity);\n"
        "aster_string_builder *aster_builder_clone(\n"
        "        const aster_string_builder *value);\n"
        "static inline void aster_builder_append(\n"
        "        aster_string_builder *builder,\n"
        "        aster_str value);\n"
        "static inline void aster_builder_append_html_escaped(\n"
        "        aster_string_builder *builder, aster_str value,\n"
        "        bool attribute);\n"
        "static inline void aster_builder_append_bool(\n"
        "        aster_string_builder *builder, bool value);\n"
        "static inline void aster_builder_append_i64(\n"
        "        aster_string_builder *builder, int64_t value);\n"
        "static inline void aster_builder_append_u64(\n"
        "        aster_string_builder *builder, uint64_t value);\n"
        "static inline void aster_builder_append_f64(\n"
        "        aster_string_builder *builder, double value);\n"
        "aster_string *aster_builder_finish(\n"
        "        aster_string_builder *builder);\n"
        "void aster_builder_drop(aster_string_builder *builder);\n"
        "bool aster_str_equal(aster_str left, aster_str right);\n"
        "void aster_console_write_str(FILE *stream, aster_str value,\n"
        "        bool newline);\n"
        "void aster_console_write_string(FILE *stream,\n"
        "        const aster_string *value, bool newline);\n"
        "aster_string *aster_i64_to_string(int64_t value);\n"
        "aster_string *aster_u64_to_string(uint64_t value);\n"
        "aster_string *aster_f32_to_string(float value);\n"
        "aster_string *aster_f64_to_string(double value);\n\n",
        output);
    if (native_runtime)
        fputs(
            "typedef struct aster_native_handle {\n"
            "    size_t references;\n"
            "    LangValue value;\n"
            "} aster_native_handle;\n"
            "static LangVM *aster_vm;\n"
            "void aster_native_handle_drop(aster_native_handle *handle);\n"
            "void aster_native_handle_drop(aster_native_handle *handle) {\n"
            "    if (handle == NULL) return;\n"
            "    if (handle->references > 1U) {\n"
            "        --handle->references;\n"
            "        return;\n"
            "    }\n"
            "    lang_value_drop(aster_vm, &handle->value);\n"
            "    free(handle);\n"
            "}\n\n",
            output);
    fputs(
        "typedef struct aster_cancellation_state {\n"
        "    size_t references;\n"
        "    bool requested;\n"
        "} aster_cancellation_state;\n"
        "static inline aster_cancellation_state *aster_cancellation_new(void) {\n"
        "    aster_cancellation_state *state = malloc(sizeof(*state));\n"
        "    if (state == NULL) {\n"
        "        fputs(\"out of memory\\n\", stderr);\n"
        "        exit(1);\n"
        "    }\n"
        "    state->references = 1U;\n"
        "    state->requested = false;\n"
        "    return state;\n"
        "}\n"
        "static inline aster_cancellation_state *aster_cancellation_retain(\n"
        "        aster_cancellation_state *state) {\n"
        "    if (state == NULL) return NULL;\n"
        "    if (state->references == SIZE_MAX) {\n"
        "        fputs(\"cancellation reference count overflow\\n\", stderr);\n"
        "        exit(1);\n"
        "    }\n"
        "    ++state->references;\n"
        "    return state;\n"
        "}\n"
        "static inline void aster_cancellation_drop(\n"
        "        aster_cancellation_state *state) {\n"
        "    if (state == NULL) return;\n"
        "    if (state->references > 1U) {\n"
        "        --state->references;\n"
        "        return;\n"
        "    }\n"
        "    free(state);\n"
        "}\n\n",
        output);
    fputs(
        "aster_url *aster_url_relative(aster_str value);\n"
        "aster_url *aster_url_fragment(aster_str value);\n"
        "aster_html *aster_html_begin(aster_str tag);\n"
        "aster_html *aster_html_begin_child(\n"
        "        aster_html *parent, aster_str tag);\n"
        "void aster_html_property(aster_html *html, aster_str name,\n"
        "        aster_str value);\n"
        "void aster_html_property_bool(aster_html *html, aster_str name,\n"
        "        bool value);\n"
        "void aster_html_property_i64(aster_html *html, aster_str name,\n"
        "        int64_t value);\n"
        "void aster_html_property_u64(aster_html *html, aster_str name,\n"
        "        uint64_t value);\n"
        "void aster_html_property_f64(aster_html *html, aster_str name,\n"
        "        double value);\n"
        "void aster_html_append_text(aster_html *html, aster_str value);\n"
        "void aster_html_append_owned_text(\n"
        "        aster_html *html, aster_string *value);\n"
        "void aster_html_append_html(aster_html *html, aster_html *child);\n"
        "aster_html *aster_html_finish(aster_html *html);\n"
        "aster_str aster_html_as_str(const aster_html *html);\n"
        "aster_string *aster_html_render(aster_html *html);\n"
        "aster_string *aster_html_to_string(const aster_html *html);\n"
        "aster_html *aster_html_unsafe_raw(aster_str value);\n"
        "aster_html *aster_html_clone(const aster_html *html);\n"
        "void aster_html_drop(aster_html *html);\n\n"
        "aster_arena *aster_arena_new(void);\n"
        "void *aster_arena_alloc(aster_arena *arena, size_t size);\n"
        "void aster_arena_reset(aster_arena *arena);\n"
        "void aster_arena_drop(aster_arena *arena);\n\n"
        "bool aster_http_path_matches(aster_str pattern, aster_str path);\n"
        "aster_str aster_http_path_param(aster_str pattern, aster_str path,"
        " aster_str name);\n\n"
        "_Noreturn void aster_trap(const char *message);\n"
        "int64_t aster_add_s(int64_t a, int64_t b,\n"
        "        int64_t minimum, int64_t maximum);\n"
        "uint64_t aster_add_u(uint64_t a, uint64_t b,\n"
        "        uint64_t maximum);\n"
        "int64_t aster_sub_s(int64_t a, int64_t b,\n"
        "        int64_t minimum, int64_t maximum);\n"
        "uint64_t aster_sub_u(uint64_t a, uint64_t b,\n"
        "        uint64_t maximum);\n"
        "int64_t aster_mul_s(int64_t a, int64_t b,\n"
        "        int64_t minimum, int64_t maximum);\n"
        "uint64_t aster_mul_u(uint64_t a, uint64_t b,\n"
        "        uint64_t maximum);\n"
        "int64_t aster_div_s(int64_t a, int64_t b,\n"
        "        int64_t minimum, int64_t maximum);\n"
        "uint64_t aster_div_u(uint64_t a, uint64_t b);\n"
        "int64_t aster_rem_s(int64_t a, int64_t b,\n"
        "        int64_t minimum, int64_t maximum);\n"
        "uint64_t aster_rem_u(uint64_t a, uint64_t b);\n"
        "int64_t aster_shift_s(int64_t value, uint64_t count,\n"
        "        unsigned width, bool right,\n"
        "        int64_t minimum, int64_t maximum);\n"
        "uint64_t aster_shift_u(uint64_t value, uint64_t count,\n"
        "        unsigned width, bool right, uint64_t maximum);\n"
        "int64_t aster_neg_s(int64_t value,\n"
        "        int64_t minimum, int64_t maximum);\n\n"
        "uint64_t aster_bits_u(uint64_t bits, unsigned width);\n"
        "int64_t aster_bits_s(uint64_t bits, unsigned width);\n\n"
        "#ifndef ASTER_EXTERNAL_RUNTIME\n"
        "static void *aster_allocate(size_t size) {\n"
        "    void *result = malloc(size);\n"
        "    if (result == NULL) {\n"
        "        fputs(\"out of memory\\n\", stderr);\n"
        "        exit(1);\n"
        "    }\n"
        "    return result;\n"
        "}\n"
        "#endif\n",
        output);
    fputs(
        "static size_t aster_format_u64(unsigned char *buffer,\n"
        "        uint64_t value) {\n"
        "    size_t length = 0U;\n"
        "    do {\n"
        "        buffer[length++] = (unsigned char)('0' + value % 10U);\n"
        "        value /= 10U;\n"
        "    } while (value != 0U);\n"
        "    for (size_t left = 0U, right = length - 1U; left < right;\n"
        "         ++left, --right) {\n"
        "        unsigned char byte = buffer[left];\n"
        "        buffer[left] = buffer[right];\n"
        "        buffer[right] = byte;\n"
        "    }\n"
        "    return length;\n"
        "}\n"
        "static size_t aster_format_i64(unsigned char *buffer,\n"
        "        int64_t value) {\n"
        "    if (value >= 0) return aster_format_u64(buffer, (uint64_t)value);\n"
        "    buffer[0] = '-';\n"
        "    uint64_t magnitude = (uint64_t)(-(value + 1)) + 1U;\n"
        "    return 1U + aster_format_u64(buffer + 1U, magnitude);\n"
        "}\n"
        "#ifndef ASTER_EXTERNAL_RUNTIME\n"
        "aster_string *aster_string_from(aster_str value) {\n"
        "    aster_string *result = aster_allocate(sizeof(*result));\n"
        "    result->references = 1U;\n"
        "    result->length = value.length;\n"
        "    result->data = value.length == 0U\n"
        "        ? NULL : aster_allocate(value.length);\n"
        "    if (value.length != 0U)\n"
        "        memcpy(result->data, value.data, value.length);\n"
        "    return result;\n"
        "}\n"
        "aster_string *aster_string_clone(const aster_string *value) {\n"
        "    if (value == NULL) return NULL;\n"
        "    aster_string *result = (aster_string *)value;\n"
        "    if (result->references == SIZE_MAX)\n"
        "        aster_trap(\"string reference count overflow\");\n"
        "    ++result->references;\n"
        "    return result;\n"
        "}\n"
        "void aster_string_drop(aster_string *value) {\n"
        "    if (value == NULL) return;\n"
        "    if (value->references > 1U) {\n"
        "        --value->references;\n"
        "        return;\n"
        "    }\n"
        "    uintptr_t inline_data = (uintptr_t)(void *)value +\n"
        "        sizeof(aster_string_owner) + 1U;\n"
        "    if ((uintptr_t)(void *)value->data != inline_data)\n"
        "        free(value->data);\n"
        "    free(value);\n"
        "}\n"
        "aster_str aster_string_as_str(const aster_string *value) {\n"
        "    return (aster_str){value->data, value->length};\n"
        "}\n"
        "aster_string_builder *aster_builder_with_capacity(\n"
        "        size_t capacity) {\n"
        "    if (capacity > SIZE_MAX - sizeof(aster_string_owner) - 1U)\n"
        "        aster_trap(\"string capacity overflow\");\n"
        "    aster_string_owner *owner = aster_allocate(\n"
        "        sizeof(*owner) + 1U + capacity);\n"
        "    aster_string_builder *result = &owner->builder;\n"
        "    result->references = 1U;\n"
        "    result->data = capacity == 0U\n"
        "        ? NULL : (unsigned char *)(owner + 1U) + 1U;\n"
        "    result->length = 0U;\n"
        "    result->capacity = capacity;\n"
        "    return result;\n"
        "}\n"
        "aster_string_builder *aster_builder_new(void) {\n"
        "    return aster_builder_with_capacity(0U);\n"
        "}\n"
        "aster_string_builder *aster_builder_clone(\n"
        "        const aster_string_builder *value) {\n"
        "    aster_string_builder *result = aster_builder_new();\n"
        "    aster_builder_append(result,\n"
        "        (aster_str){value->data, value->length});\n"
        "    return result;\n"
        "}\n"
        "#endif\n",
        output);
    fputs(
        "static inline void aster_builder_reserve(\n"
        "        aster_string_builder *builder,\n"
        "        size_t additional) {\n"
        "    if (additional > SIZE_MAX - builder->length)\n"
        "        aster_trap(\"string capacity overflow\");\n"
        "    size_t needed = builder->length + additional;\n"
        "    if (needed > builder->capacity) {\n"
        "        size_t capacity = builder->capacity == 0U\n"
        "            ? 64U : builder->capacity;\n"
        "        while (capacity < needed) {\n"
        "            if (capacity > SIZE_MAX / 2U)\n"
        "                aster_trap(\"string capacity overflow\");\n"
        "            capacity *= 2U;\n"
        "        }\n"
        "        aster_string_owner *owner =\n"
        "            (aster_string_owner *)builder;\n"
        "        unsigned char *inline_data =\n"
        "            (unsigned char *)(owner + 1U) + 1U;\n"
        "        unsigned char *data;\n"
        "        if (builder->data == inline_data) {\n"
        "            data = malloc(capacity);\n"
        "            if (builder->length != 0U)\n"
        "                memcpy(data, builder->data, builder->length);\n"
        "        } else {\n"
        "            data = realloc(builder->data, capacity);\n"
        "        }\n"
        "        if (data == NULL) aster_trap(\"out of memory\");\n"
        "        builder->data = data;\n"
        "        builder->capacity = capacity;\n"
        "    }\n"
        "}\n"
        "static inline void aster_builder_append(\n"
        "        aster_string_builder *builder,\n"
        "        aster_str value) {\n"
        "    aster_builder_reserve(builder, value.length);\n"
        "    if (value.length != 0U)\n"
        "        memcpy(builder->data + builder->length,\n"
        "               value.data, value.length);\n"
        "    builder->length += value.length;\n"
        "}\n",
        output);
    fputs(
        "static inline void aster_builder_append_html_escaped(\n"
        "        aster_string_builder *builder, aster_str value,\n"
        "        bool attribute) {\n"
        "    size_t escaped = value.length;\n"
        "    for (size_t i = 0U; i < value.length; ++i) {\n"
        "        size_t extra = 0U;\n"
        "        switch (value.data[i]) {\n"
        "            case '&': extra = 4U; break;\n"
        "            case '<': case '>': extra = 3U; break;\n"
        "            case '\"': if (attribute) extra = 5U; break;\n"
        "            case '\\'': if (attribute) extra = 4U; break;\n"
        "            default: break;\n"
        "        }\n"
        "        if (extra > SIZE_MAX - escaped)\n"
        "            aster_trap(\"string capacity overflow\");\n"
        "        escaped += extra;\n"
        "    }\n"
        "    aster_builder_reserve(builder, escaped);\n"
        "    size_t write = builder->length;\n"
        "    for (size_t i = 0U; i < value.length; ++i) {\n"
        "        const char *replacement = NULL;\n"
        "        size_t replacement_length = 0U;\n"
        "        switch (value.data[i]) {\n"
        "            case '&': replacement = \"&amp;\";\n"
        "                replacement_length = 5U; break;\n"
        "            case '<': replacement = \"&lt;\";\n"
        "                replacement_length = 4U; break;\n"
        "            case '>': replacement = \"&gt;\";\n"
        "                replacement_length = 4U; break;\n"
        "            case '\"': if (attribute) {\n"
        "                replacement = \"&quot;\";\n"
        "                replacement_length = 6U; } break;\n"
        "            case '\\'': if (attribute) {\n"
        "                replacement = \"&#39;\";\n"
        "                replacement_length = 5U; } break;\n"
        "            default: break;\n"
        "        }\n"
        "        if (replacement == NULL) {\n"
        "            builder->data[write++] = value.data[i];\n"
        "        } else {\n"
        "            memcpy(builder->data + write, replacement,\n"
        "                   replacement_length);\n"
        "            write += replacement_length;\n"
        "        }\n"
        "    }\n"
        "    builder->length = write;\n"
        "}\n",
        output);
    fputs(
        "static inline void aster_builder_append_bool(\n"
        "        aster_string_builder *builder, bool value) {\n"
        "    const char *text = value ? \"true\" : \"false\";\n"
        "    aster_builder_append(builder, (aster_str){\n"
        "        (const unsigned char *)text, strlen(text)});\n"
        "}\n"
        "static inline void aster_builder_append_i64(\n"
        "        aster_string_builder *builder, int64_t value) {\n"
        "    unsigned char buffer[32];\n"
        "    size_t length = aster_format_i64(buffer, value);\n"
        "    if (length > sizeof(buffer))\n"
        "        aster_trap(\"could not format integer\");\n"
        "    aster_builder_append(builder, (aster_str){\n"
        "        buffer, length});\n"
        "}\n"
        "static inline void aster_builder_append_u64(\n"
        "        aster_string_builder *builder, uint64_t value) {\n"
        "    unsigned char buffer[32];\n"
        "    size_t length = aster_format_u64(buffer, value);\n"
        "    if (length > sizeof(buffer))\n"
        "        aster_trap(\"could not format integer\");\n"
        "    aster_builder_append(builder, (aster_str){\n"
        "        buffer, length});\n"
        "}\n"
        "static inline void aster_builder_append_f64(\n"
        "        aster_string_builder *builder, double value) {\n"
        "    unsigned char buffer[64];\n"
        "    int length = snprintf((char *)buffer, sizeof(buffer),\n"
        "                          \"%g\", value);\n"
        "    if (length < 0 || (size_t)length >= sizeof(buffer))\n"
        "        aster_trap(\"could not format float\");\n"
        "    aster_builder_append(builder, (aster_str){\n"
        "        buffer, (size_t)length});\n"
        "}\n"
        "#ifndef ASTER_EXTERNAL_RUNTIME\n"
        "aster_string *aster_builder_finish(\n"
        "        aster_string_builder *builder) {\n"
        "    unsigned char *data = builder->data;\n"
        "    size_t length = builder->length;\n"
        "    aster_string_owner *owner = (aster_string_owner *)builder;\n"
        "    owner->string = (aster_string){1U, data, length};\n"
        "    return &owner->string;\n"
        "}\n"
        "void aster_builder_drop(aster_string_builder *builder) {\n"
        "    if (builder == NULL) return;\n"
        "    aster_string_owner *owner = (aster_string_owner *)builder;\n"
        "    if (builder->data != (unsigned char *)(owner + 1U) + 1U)\n"
        "        free(builder->data);\n"
        "    free(builder);\n"
        "}\n"
        "bool aster_str_equal(aster_str left, aster_str right) {\n"
        "    return left.length == right.length &&\n"
        "        (left.length == 0U ||\n"
        "         memcmp(left.data, right.data, left.length) == 0);\n"
        "}\n"
        "void aster_console_write_str(FILE *stream, aster_str value,\n"
        "        bool newline) {\n"
        "    if (value.length != 0U)\n"
        "        (void)fwrite(value.data, 1U, value.length, stream);\n"
        "    if (newline) fputc('\\n', stream);\n"
        "    (void)fflush(stream);\n"
        "}\n"
        "void aster_console_write_string(FILE *stream,\n"
        "        const aster_string *value, bool newline) {\n"
        "    aster_console_write_str(\n"
        "        stream, aster_string_as_str(value), newline);\n"
        "}\n"
        "aster_string *aster_i64_to_string(int64_t value) {\n"
        "    unsigned char buffer[32];\n"
        "    size_t length = aster_format_i64(buffer, value);\n"
        "    return aster_string_from((aster_str){buffer, length});\n"
        "}\n"
        "aster_string *aster_u64_to_string(uint64_t value) {\n"
        "    unsigned char buffer[32];\n"
        "    size_t length = aster_format_u64(buffer, value);\n"
        "    return aster_string_from((aster_str){buffer, length});\n"
        "}\n"
        "aster_string *aster_f32_to_string(float value) {\n"
        "    unsigned char buffer[64];\n"
        "    int length = snprintf((char *)buffer, sizeof(buffer),\n"
        "        \"%.9g\", (double)value);\n"
        "    if (length < 0 || (size_t)length >= sizeof(buffer))\n"
        "        aster_trap(\"could not format float\");\n"
        "    return aster_string_from((aster_str){buffer, (size_t)length});\n"
        "}\n"
        "aster_string *aster_f64_to_string(double value) {\n"
        "    unsigned char buffer[64];\n"
        "    int length = snprintf((char *)buffer, sizeof(buffer),\n"
        "        \"%.17g\", value);\n"
        "    if (length < 0 || (size_t)length >= sizeof(buffer))\n"
        "        aster_trap(\"could not format double\");\n"
        "    return aster_string_from((aster_str){buffer, (size_t)length});\n"
        "}\n"
        "\n",
        output);
    fputs(
        "_Noreturn void aster_trap(const char *message) {\n"
        "    fputs(message, stderr);\n"
        "    fputc('\\n', stderr);\n"
        "    exit(1);\n"
        "}\n"
        "aster_arena *aster_arena_new(void) {\n"
        "    aster_arena *arena = aster_allocate(sizeof(*arena));\n"
        "    arena->blocks = NULL;\n"
        "    return arena;\n"
        "}\n"
        "void *aster_arena_alloc(aster_arena *arena, size_t size) {\n"
        "    if (arena == NULL) aster_trap(\"allocation through null Arena\");\n"
        "    aster_arena_block *block = aster_allocate(sizeof(*block));\n"
        "    block->data = aster_allocate(size == 0U ? 1U : size);\n"
        "    memset(block->data, 0, size == 0U ? 1U : size);\n"
        "    block->next = arena->blocks;\n"
        "    arena->blocks = block;\n"
        "    return block->data;\n"
        "}\n"
        "void aster_arena_reset(aster_arena *arena) {\n"
        "    if (arena == NULL) return;\n"
        "    aster_arena_block *block = arena->blocks;\n"
        "    while (block != NULL) {\n"
        "        aster_arena_block *next = block->next;\n"
        "        free(block->data);\n"
        "        free(block);\n"
        "        block = next;\n"
        "    }\n"
        "    arena->blocks = NULL;\n"
        "}\n"
        "void aster_arena_drop(aster_arena *arena) {\n"
        "    if (arena == NULL) return;\n"
        "    aster_arena_reset(arena);\n"
        "    free(arena);\n"
        "}\n",
        output);
    fputs(
        "int64_t aster_add_s(int64_t a, int64_t b,\n"
        "        int64_t minimum, int64_t maximum) {\n"
        "    if ((b > 0 && a > maximum - b) ||\n"
        "        (b < 0 && a < minimum - b)) aster_trap(\"integer overflow\");\n"
        "    return a + b;\n"
        "}\n"
        "uint64_t aster_add_u(uint64_t a, uint64_t b,\n"
        "        uint64_t maximum) {\n"
        "    if (b > maximum || a > maximum - b) aster_trap(\"integer overflow\");\n"
        "    return a + b;\n"
        "}\n"
        "int64_t aster_sub_s(int64_t a, int64_t b,\n"
        "        int64_t minimum, int64_t maximum) {\n"
        "    if ((b > 0 && a < minimum + b) ||\n"
        "        (b < 0 && a > maximum + b)) aster_trap(\"integer overflow\");\n"
        "    return a - b;\n"
        "}\n"
        "uint64_t aster_sub_u(uint64_t a, uint64_t b,\n"
        "        uint64_t maximum) {\n"
        "    (void)maximum;\n"
        "    if (a < b) aster_trap(\"integer overflow\");\n"
        "    return a - b;\n"
        "}\n"
        "int64_t aster_mul_s(int64_t a, int64_t b,\n"
        "        int64_t minimum, int64_t maximum) {\n"
        "    if (a != 0 && b != 0) {\n"
        "        if ((a == -1 && b == minimum) ||\n"
        "            (b == -1 && a == minimum)) aster_trap(\"integer overflow\");\n"
        "        if (a > 0) {\n"
        "            if ((b > 0 && a > maximum / b) ||\n"
        "                (b < 0 && b < minimum / a)) aster_trap(\"integer overflow\");\n"
        "        } else if ((b > 0 && a < minimum / b) ||\n"
        "                   (b < 0 && a < maximum / b)) {\n"
        "            aster_trap(\"integer overflow\");\n"
        "        }\n"
        "    }\n"
        "    return a * b;\n"
        "}\n"
        "uint64_t aster_mul_u(uint64_t a, uint64_t b,\n"
        "        uint64_t maximum) {\n"
        "    if (b != 0 && a > maximum / b) aster_trap(\"integer overflow\");\n"
        "    return a * b;\n"
        "}\n"
        "int64_t aster_div_s(int64_t a, int64_t b,\n"
        "        int64_t minimum, int64_t maximum) {\n"
        "    (void)maximum;\n"
        "    if (b == 0) aster_trap(\"division by zero\");\n"
        "    if (a == minimum && b == -1) aster_trap(\"integer overflow\");\n"
        "    return a / b;\n"
        "}\n"
        "uint64_t aster_div_u(uint64_t a, uint64_t b) {\n"
        "    if (b == 0) aster_trap(\"division by zero\");\n"
        "    return a / b;\n"
        "}\n"
        "int64_t aster_rem_s(int64_t a, int64_t b,\n"
        "        int64_t minimum, int64_t maximum) {\n"
        "    (void)maximum;\n"
        "    if (b == 0) aster_trap(\"division by zero\");\n"
        "    if (a == minimum && b == -1) return 0;\n"
        "    return a % b;\n"
        "}\n"
        "uint64_t aster_rem_u(uint64_t a, uint64_t b) {\n"
        "    if (b == 0) aster_trap(\"division by zero\");\n"
        "    return a % b;\n"
        "}\n"
        "int64_t aster_shift_s(int64_t value, uint64_t count,\n"
        "        unsigned width, bool right,\n"
        "        int64_t minimum, int64_t maximum) {\n"
        "    if (width == 0U || count >= width) aster_trap(\"invalid shift count\");\n"
        "    if (right) {\n"
        "        if (count == 63U) return value < 0 ? -1 : 0;\n"
        "        int64_t divisor = INT64_C(1) << (unsigned)count;\n"
        "        int64_t result = value / divisor;\n"
        "        if (value < 0 && value % divisor != 0) --result;\n"
        "        return result;\n"
        "    }\n"
        "    if (count == 63U) {\n"
        "        if (value != 0) aster_trap(\"integer shift overflow\");\n"
        "        return 0;\n"
        "    }\n"
        "    return aster_mul_s(value, INT64_C(1) << (unsigned)count,\n"
        "            minimum, maximum);\n"
        "}\n"
        "uint64_t aster_shift_u(uint64_t value, uint64_t count,\n"
        "        unsigned width, bool right, uint64_t maximum) {\n"
        "    if (width == 0U || count >= width) aster_trap(\"invalid shift count\");\n"
        "    if (right) return value >> (unsigned)count;\n"
        "    if (value > (maximum >> (unsigned)count))\n"
        "        aster_trap(\"integer shift overflow\");\n"
        "    return value << (unsigned)count;\n"
        "}\n"
        "int64_t aster_neg_s(int64_t value,\n"
        "        int64_t minimum, int64_t maximum) {\n"
        "    (void)maximum;\n"
        "    if (value == minimum) aster_trap(\"integer overflow\");\n"
        "    return -value;\n"
        "}\n"
        "uint64_t aster_bits_u(uint64_t bits, unsigned width) {\n"
        "    uint64_t mask = width == 64U\n"
        "        ? UINT64_MAX : (UINT64_C(1) << width) - UINT64_C(1);\n"
        "    return bits & mask;\n"
        "}\n"
        "int64_t aster_bits_s(uint64_t bits, unsigned width) {\n"
        "    uint64_t mask = width == 64U\n"
        "        ? UINT64_MAX : (UINT64_C(1) << width) - UINT64_C(1);\n"
        "    bits &= mask;\n"
        "    uint64_t sign = UINT64_C(1) << (width - 1U);\n"
        "    if ((bits & sign) == 0U) return (int64_t)bits;\n"
        "    uint64_t magnitude = ((~bits) & mask) + UINT64_C(1);\n"
        "    return magnitude == (UINT64_C(1) << 63U)\n"
        "        ? INT64_MIN : -(int64_t)magnitude;\n"
        "}\n\n",
        output);
}

void c_backend_emit_html_prelude(FILE *output,
                                 const char *css_asset_href) {
    if (css_asset_href == NULL)
        fputs("static const aster_str aster_css_asset_href = {NULL, 0U};\n", output);
    else
        fprintf(output,
                "static const aster_str aster_css_asset_href = "
                "{(const unsigned char *)\"%s\", %zuU};\n",
                css_asset_href, strlen(css_asset_href));
    fputs(
        "static inline void aster_html_reserve(aster_html *html,\n"
        "        size_t additional) {\n"
        "    if (html->suppressed) return;\n"
        "    aster_html_storage *storage = html->storage;\n"
        "    if (additional > SIZE_MAX - storage->length)\n"
        "        aster_trap(\"Html value is too large\");\n"
        "    size_t required = storage->length + additional;\n"
        "    if (required <= storage->capacity) return;\n"
        "    size_t capacity = storage->capacity == 0U\n"
        "        ? 128U : storage->capacity;\n"
        "    while (capacity < required) {\n"
        "        if (capacity > SIZE_MAX / 2U) {\n"
        "            capacity = required;\n"
        "            break;\n"
        "        }\n"
        "        capacity *= 2U;\n"
        "    }\n"
        "    unsigned char *grown = realloc(storage->data, capacity);\n"
        "    if (grown == NULL) aster_trap(\"out of memory\");\n"
        "    storage->data = grown;\n"
        "    storage->capacity = capacity;\n"
        "}\n"
        "static inline void aster_html_bytes(aster_html *html,\n"
        "        const unsigned char *data, size_t length) {\n"
        "    if (html->suppressed) return;\n"
        "    if (data == NULL && length != 0U)\n"
        "        aster_trap(\"invalid Html text\");\n"
        "    aster_html_reserve(html, length);\n"
        "    aster_html_storage *storage = html->storage;\n"
        "    if (length != 0U)\n"
        "        memcpy(storage->data + storage->length, data, length);\n"
        "    storage->length += length;\n"
        "}\n"
        "static void aster_html_literal(aster_html *html,\n"
        "        const char *text) {\n"
        "    aster_html_bytes(html, (const unsigned char *)text,\n"
        "                      strlen(text));\n"
        "}\n",
        output);
    fputs(
        "static bool aster_html_style_equal(aster_str left,\n"
        "        aster_str right) {\n"
        "    return left.length == right.length &&\n"
        "        (left.length == 0U ||\n"
        "         memcmp(left.data, right.data, left.length) == 0);\n"
        "}\n"
        "static bool aster_html_style_registered(\n"
        "        const aster_html_storage *storage, aster_str id) {\n"
        "    for (size_t i = 0U; i < storage->style_id_count; ++i)\n"
        "        if (aster_html_style_equal(storage->style_ids[i], id))\n"
        "            return true;\n"
        "    return false;\n"
        "}\n"
        "static void aster_html_register_style(\n"
        "        aster_html_storage *storage, aster_str id) {\n"
        "    if (aster_html_style_registered(storage, id)) return;\n"
        "    if (storage->style_id_count == storage->style_id_capacity) {\n"
        "        size_t capacity = storage->style_id_capacity == 0U\n"
        "            ? 4U : storage->style_id_capacity * 2U;\n"
        "        aster_str *grown = realloc(storage->style_ids,\n"
        "            capacity * sizeof(*grown));\n"
        "        if (grown == NULL) aster_trap(\"out of memory\");\n"
        "        storage->style_ids = grown;\n"
        "        storage->style_id_capacity = capacity;\n"
        "    }\n"
        "    storage->style_ids[storage->style_id_count++] = id;\n"
        "}\n"
        "static void aster_html_record_style(aster_html_storage *storage,\n"
        "        aster_str id, size_t start, size_t end) {\n"
        "    if (storage->style_occurrence_count ==\n"
        "            storage->style_occurrence_capacity) {\n"
        "        size_t capacity = storage->style_occurrence_capacity == 0U\n"
        "            ? 4U : storage->style_occurrence_capacity * 2U;\n"
        "        aster_html_style_occurrence *grown = realloc(\n"
        "            storage->style_occurrences, capacity * sizeof(*grown));\n"
        "        if (grown == NULL) aster_trap(\"out of memory\");\n"
        "        storage->style_occurrences = grown;\n"
        "        storage->style_occurrence_capacity = capacity;\n"
        "    }\n"
        "    storage->style_occurrences[storage->style_occurrence_count++] =\n"
        "        (aster_html_style_occurrence){id, start, end};\n"
        "}\n"
        "static void aster_html_escape(aster_html *html, aster_str value,\n"
        "        bool attribute) {\n"
        "    size_t start = 0U;\n"
        "    for (size_t i = 0U; i < value.length; ++i) {\n"
        "        const char *replacement = NULL;\n"
        "        switch (value.data[i]) {\n"
        "            case '&': replacement = \"&amp;\"; break;\n"
        "            case '<': replacement = \"&lt;\"; break;\n"
        "            case '>': replacement = \"&gt;\"; break;\n"
        "            case '\"': if (attribute) replacement = \"&quot;\"; break;\n"
        "            case '\\'': if (attribute) replacement = \"&#39;\"; break;\n"
        "            default: break;\n"
        "        }\n"
        "        if (replacement == NULL) continue;\n"
        "        if (i != start)\n"
        "            aster_html_bytes(html, value.data + start, i - start);\n"
        "        aster_html_literal(html, replacement);\n"
        "        start = i + 1U;\n"
        "    }\n"
        "    if (start != value.length)\n"
        "        aster_html_bytes(html, value.data + start, value.length - start);\n"
        "}\n"
        "static void aster_html_close_open(aster_html *html) {\n"
        "    if (html->suppressed) { html->open = false; return; }\n"
        "    if (!html->open) return;\n"
        "    aster_html_literal(html, \">\");\n"
        "    html->open = false;\n"
        "}\n"
        "static bool aster_html_is_raw_text(const aster_html *html) {\n"
        "    return (html->tag_length == 6U &&\n"
        "            memcmp(html->tag, \"script\", 6U) == 0) ||\n"
        "           (html->tag_length == 5U &&\n"
        "            memcmp(html->tag, \"style\", 5U) == 0);\n"
        "}\n"
        "aster_url *aster_url_relative(aster_str value) {\n"
        "    return (aster_url *)aster_string_from(value);\n"
        "}\n"
        "aster_url *aster_url_fragment(aster_str value) {\n"
        "    aster_url *result = aster_allocate(sizeof(*result));\n"
        "    result->references = 1U;\n"
        "    if (value.length == SIZE_MAX)\n"
        "        aster_trap(\"Url value is too large\");\n"
        "    result->length = value.length + 1U;\n"
        "    result->data = aster_allocate(result->length);\n"
        "    result->data[0] = '#';\n"
        "    if (value.length != 0U)\n"
        "        memcpy(result->data + 1U, value.data, value.length);\n"
        "    return result;\n"
        "}\n",
        output);
    fputs(
        "aster_html *aster_html_begin(aster_str tag) {\n"
        "    aster_html_owner *owner = aster_allocate(\n"
        "        sizeof(*owner) + sizeof(aster_html_storage));\n"
        "    aster_html *html = &owner->html;\n"
        "    *html = (aster_html){0};\n"
        "    html->storage = (aster_html_storage *)(owner + 1U);\n"
        "    *html->storage = (aster_html_storage){0};\n"
        "    if (tag.length == 9U &&\n"
        "        memcmp(tag.data, \"#fragment\", 9U) == 0)\n"
        "        return html;\n"
        "    html->tag_length = tag.length;\n"
        "    html->tag = tag.data;\n"
        "    html->open = true;\n"
        "    html->start = html->storage->length;\n"
        "    aster_html_literal(html, \"<\");\n"
        "    aster_html_bytes(html, tag.data, tag.length);\n"
        "    return html;\n"
        "}\n"
        "aster_html *aster_html_begin_child(\n"
        "        aster_html *parent, aster_str tag) {\n"
        "    if (parent == NULL) aster_trap(\"invalid parent Html builder\");\n"
        "    aster_html_close_open(parent);\n"
        "    aster_html_storage *storage = parent->storage;\n"
        "    if (storage->child_count >= 32U)\n"
        "        aster_trap(\"Html element nesting limit exceeded\");\n"
        "    aster_html *html =\n"
        "        &storage->children[storage->child_count++];\n"
        "    *html = (aster_html){0};\n"
        "    html->storage = storage;\n"
        "    html->attached = true;\n"
        "    if (tag.length == 9U &&\n"
        "        memcmp(tag.data, \"#fragment\", 9U) == 0)\n"
        "        return html;\n"
        "    html->tag = tag.data;\n"
        "    html->tag_length = tag.length;\n"
        "    html->open = true;\n"
        "    html->start = storage->length;\n"
        "    aster_html_literal(html, \"<\");\n"
        "    aster_html_bytes(html, tag.data, tag.length);\n"
        "    return html;\n"
        "}\n"
        "void aster_html_property(aster_html *html, aster_str name,\n"
        "        aster_str value) {\n"
        "    if (!html->open)\n"
        "        aster_trap(\"cannot add a property after element children\");\n"
        "    aster_html_literal(html, \" \");\n"
        "    aster_html_bytes(html, name.data, name.length);\n"
        "    aster_html_literal(html, \"=\\\"\");\n"
        "    aster_html_escape(html, value, true);\n"
        "    aster_html_literal(html, \"\\\"\");\n"
        "}\n"
        "static inline void aster_html_property_literal(\n"
        "        aster_html *html, aster_str name, aster_str value) {\n"
        "    if (!html->open)\n"
        "        aster_trap(\"cannot add a property after element children\");\n"
        "    aster_html_literal(html, \" \");\n"
        "    aster_html_bytes(html, name.data, name.length);\n"
        "    aster_html_literal(html, \"=\\\"\");\n"
        "    aster_html_bytes(html, value.data, value.length);\n"
        "    aster_html_literal(html, \"\\\"\");\n"
        "}\n",
        output);
    fputs(
        "void aster_html_property_bool(aster_html *html, aster_str name,\n"
        "        bool value) {\n"
        "    if (!html->open)\n"
        "        aster_trap(\"cannot add a property after element children\");\n"
        "    if (!value) return;\n"
        "    static const char prefix[] = \"data-aster-static-style-\";\n"
        "    if (html->tag_length == 5U &&\n"
        "        memcmp(html->tag, \"style\", 5U) == 0 &&\n"
        "        name.length > sizeof(prefix) - 1U &&\n"
        "        memcmp(name.data, prefix, sizeof(prefix) - 1U) == 0) {\n"
        "        html->static_style_id = name;\n"
        "        bool registered =\n"
        "            aster_html_style_registered(html->storage, name);\n"
        "        if (aster_css_asset_href.length != 0U) {\n"
        "            html->storage->length = html->start;\n"
        "            if (!registered) {\n"
        "                aster_html_register_style(html->storage, name);\n"
        "                aster_html_literal(html,\n"
        "                    \"<link rel=\\\"stylesheet\\\" href=\\\"\");\n"
        "                aster_html_bytes(html, aster_css_asset_href.data,\n"
        "                    aster_css_asset_href.length);\n"
        "                aster_html_literal(html, \"\\\">\");\n"
        "                aster_html_record_style(html->storage, name,\n"
        "                    html->start, html->storage->length);\n"
        "            }\n"
        "            html->suppressed = true;\n"
        "            html->open = false;\n"
        "        } else if (registered) {\n"
        "            html->storage->length = html->start;\n"
        "            html->suppressed = true;\n"
        "            html->open = false;\n"
        "        } else {\n"
        "            aster_html_register_style(html->storage, name);\n"
        "        }\n"
        "        return;\n"
        "    }\n"
        "    aster_html_literal(html, \" \");\n"
        "    aster_html_bytes(html, name.data, name.length);\n"
        "}\n"
        "void aster_html_property_i64(aster_html *html, aster_str name,\n"
        "        int64_t value) {\n"
        "    unsigned char text[32];\n"
        "    size_t length = aster_format_i64(text, value);\n"
        "    aster_html_property(html, name, (aster_str){\n"
        "        text, length});\n"
        "}\n"
        "void aster_html_property_u64(aster_html *html, aster_str name,\n"
        "        uint64_t value) {\n"
        "    unsigned char text[32];\n"
        "    size_t length = aster_format_u64(text, value);\n"
        "    aster_html_property(html, name, (aster_str){\n"
        "        text, length});\n"
        "}\n"
        "void aster_html_property_f64(aster_html *html, aster_str name,\n"
        "        double value) {\n"
        "    char text[64];\n"
        "    int length = snprintf(text, sizeof(text), \"%g\", value);\n"
        "    aster_html_property(html, name, (aster_str){\n"
        "        (const unsigned char *)text, (size_t)length});\n"
        "}\n",
        output);
    fputs(
        "static inline bool aster_css_atom(aster_str value) {\n"
        "    if (value.length == 0U) return false;\n"
        "    for (size_t i = 0U; i < value.length; ++i) {\n"
        "        unsigned char byte = value.data[i];\n"
        "        if ((byte >= 'a' && byte <= 'z') ||\n"
        "            (byte >= 'A' && byte <= 'Z') ||\n"
        "            (byte >= '0' && byte <= '9') ||\n"
        "            byte == '#' || byte == '_' || byte == '-' ||\n"
        "            byte == '.' || byte == '%' || byte == '+')\n"
        "            continue;\n"
        "        return false;\n"
        "    }\n"
        "    return true;\n"
        "}\n",
        output);
    fputs(
        "static inline void aster_html_interpolation_begin(\n"
        "        aster_html *html, aster_str name) {\n"
        "    if (!html->open)\n"
        "        aster_trap(\"cannot add a property after element children\");\n"
        "    aster_html_literal(html, \" \");\n"
        "    aster_html_bytes(html, name.data, name.length);\n"
        "    aster_html_literal(html, \"=\\\"\");\n"
        "}\n"
        "static inline void aster_html_interpolation_end(aster_html *html) {\n"
        "    aster_html_literal(html, \"\\\"\");\n"
        "}\n"
        "static inline void aster_html_interpolation_str(\n"
        "        aster_html *html, aster_str value, bool attribute) {\n"
        "    if (!attribute) aster_html_close_open(html);\n"
        "    if (!attribute && aster_html_is_raw_text(html))\n"
        "        aster_html_bytes(html, value.data, value.length);\n"
        "    else\n"
        "        aster_html_escape(html, value, attribute);\n"
        "}\n"
        "static inline void aster_html_css_value_str(\n"
        "        aster_html *html, aster_str value, bool attribute) {\n"
        "    if (!aster_css_atom(value))\n"
        "        aster_trap(\"unsafe CSS custom property value\");\n"
        "    aster_html_interpolation_str(html, value, attribute);\n"
        "}\n",
        output);
    fputs(
        "static inline void aster_html_interpolation_literal(\n"
        "        aster_html *html, aster_str value, bool attribute) {\n"
        "    if (!attribute) aster_html_close_open(html);\n"
        "    aster_html_bytes(html, value.data, value.length);\n"
        "}\n"
        "static inline void aster_html_interpolation_bool(\n"
        "        aster_html *html, bool value, bool attribute) {\n"
        "    if (!attribute) aster_html_close_open(html);\n"
        "    aster_html_literal(html, value ? \"true\" : \"false\");\n"
        "}\n"
        "static inline void aster_html_interpolation_i64(\n"
        "        aster_html *html, int64_t value, bool attribute) {\n"
        "    if (!attribute) aster_html_close_open(html);\n"
        "    unsigned char text[32];\n"
        "    size_t length = aster_format_i64(text, value);\n"
        "    aster_html_bytes(html, text, length);\n"
        "}\n"
        "static inline void aster_html_interpolation_u64(\n"
        "        aster_html *html, uint64_t value, bool attribute) {\n"
        "    if (!attribute) aster_html_close_open(html);\n"
        "    unsigned char text[32];\n"
        "    size_t length = aster_format_u64(text, value);\n"
        "    aster_html_bytes(html, text, length);\n"
        "}\n"
        "static inline void aster_html_interpolation_f64(\n"
        "        aster_html *html, double value, bool attribute) {\n"
        "    if (!attribute) aster_html_close_open(html);\n"
        "    char text[64];\n"
        "    int length = snprintf(text, sizeof(text), \"%g\", value);\n"
        "    aster_html_bytes(html, (const unsigned char *)text,\n"
        "                      (size_t)length);\n"
        "}\n"
        "void aster_html_append_text(aster_html *html, aster_str value) {\n"
        "    aster_html_close_open(html);\n"
        "    if (aster_html_is_raw_text(html))\n"
        "        aster_html_bytes(html, value.data, value.length);\n"
        "    else\n"
        "        aster_html_escape(html, value, false);\n"
        "}\n"
        "void aster_html_append_owned_text(\n"
        "        aster_html *html, aster_string *value) {\n"
        "    aster_html_append_text(html, aster_string_as_str(value));\n"
        "    aster_string_drop(value);\n"
        "}\n"
        "static void aster_html_append_storage(aster_html *html,\n"
        "        const aster_html_storage *child) {\n"
        "    if (child->style_occurrence_count == 0U) {\n"
        "        aster_html_bytes(html, child->data, child->length);\n"
        "        return;\n"
        "    }\n"
        "    aster_html_storage *target = html->storage;\n"
        "    size_t cursor = 0U;\n"
        "    for (size_t i = 0U; i < child->style_occurrence_count; ++i) {\n"
        "        const aster_html_style_occurrence *item =\n"
        "            &child->style_occurrences[i];\n"
        "        if (item->start < cursor || item->end < item->start ||\n"
        "            item->end > child->length) continue;\n"
        "        aster_html_bytes(html, child->data + cursor,\n"
        "            item->start - cursor);\n"
        "        if (!aster_html_style_registered(target, item->id)) {\n"
        "            size_t start = target->length;\n"
        "            aster_html_register_style(target, item->id);\n"
        "            aster_html_bytes(html, child->data + item->start,\n"
        "                item->end - item->start);\n"
        "            aster_html_record_style(target, item->id, start,\n"
        "                target->length);\n"
        "        }\n"
        "        cursor = item->end;\n"
        "    }\n"
        "    aster_html_bytes(html, child->data + cursor,\n"
        "        child->length - cursor);\n"
        "}\n"
        "void aster_html_append_html(aster_html *html, aster_html *child) {\n"
        "    aster_html_close_open(html);\n"
        "    if (html->storage != child->storage)\n"
        "        aster_html_append_storage(html, child->storage);\n"
        "    aster_html_drop(child);\n"
        "}\n",
        output);
    fputs(
        "static bool aster_html_is_void(const aster_html *html) {\n"
        "    static const struct {\n"
        "        const char *name;\n"
        "        size_t length;\n"
        "    } tags[] = {\n"
        "        {\"area\", 4U}, {\"base\", 4U}, {\"br\", 2U},\n"
        "        {\"col\", 3U}, {\"embed\", 5U}, {\"hr\", 2U},\n"
        "        {\"img\", 3U}, {\"input\", 5U}, {\"link\", 4U},\n"
        "        {\"meta\", 4U}, {\"param\", 5U}, {\"source\", 6U},\n"
        "        {\"track\", 5U}, {\"wbr\", 3U}\n"
        "    };\n"
        "    for (size_t i = 0U; i < sizeof(tags) / sizeof(tags[0]); ++i)\n"
        "        if (html->tag_length == tags[i].length &&\n"
        "            memcmp(html->tag, tags[i].name, tags[i].length) == 0)\n"
        "            return true;\n"
        "    return false;\n"
        "}\n",
        output);
    fputs(
        "aster_html *aster_html_finish(aster_html *html) {\n"
        "    if (html->suppressed) return html;\n"
        "    aster_html_close_open(html);\n"
        "    if (html->tag_length != 0U && !aster_html_is_void(html)) {\n"
        "        aster_html_literal(html, \"</\");\n"
        "        aster_html_bytes(html, html->tag, html->tag_length);\n"
        "        aster_html_literal(html, \">\");\n"
        "    }\n"
        "    if (html->static_style_id.data != NULL)\n"
        "        aster_html_record_style(html->storage,\n"
        "            html->static_style_id, html->start,\n"
        "            html->storage->length);\n"
        "    return html;\n"
        "}\n"
        "aster_str aster_html_as_str(const aster_html *html) {\n"
        "    if (html == NULL || html->attached || html->open)\n"
        "        aster_trap(\"cannot borrow unfinished or attached Html\");\n"
        "    return (aster_str){\n"
        "        html->storage->data, html->storage->length};\n"
        "}\n"
        "aster_string *aster_html_render(aster_html *html) {\n"
        "    if (html->attached)\n"
        "        aster_trap(\"cannot render an attached Html child\");\n"
        "    unsigned char *data = html->storage->data;\n"
        "    size_t length = html->storage->length;\n"
        "    free(html->storage->style_ids);\n"
        "    free(html->storage->style_occurrences);\n"
        "    aster_html_owner *owner = (aster_html_owner *)html;\n"
        "    owner->string = (aster_string){1U, data, length};\n"
        "    return &owner->string;\n"
        "}\n"
        "aster_string *aster_html_to_string(const aster_html *html) {\n"
        "    return aster_string_from(aster_html_as_str(html));\n"
        "}\n"
        "aster_html *aster_html_unsafe_raw(aster_str value) {\n"
        "    aster_html *html = aster_html_begin(\n"
        "        (aster_str){(const unsigned char *)\"#fragment\", 9U});\n"
        "    aster_html_bytes(html, value.data, value.length);\n"
        "    return html;\n"
        "}\n",
        output);
    fputs(
        "aster_html *aster_html_clone(const aster_html *source) {\n"
        "    aster_html_owner *owner = aster_allocate(\n"
        "        sizeof(*owner) + sizeof(aster_html_storage));\n"
        "    aster_html *copy = &owner->html;\n"
        "    *copy = (aster_html){0};\n"
        "    copy->storage = (aster_html_storage *)(owner + 1U);\n"
        "    *copy->storage = (aster_html_storage){0};\n"
        "    copy->storage->length = source->storage->length;\n"
        "    copy->storage->capacity = source->storage->length;\n"
        "    copy->storage->child_count = 0U;\n"
        "    copy->storage->data = copy->storage->capacity == 0U\n"
        "        ? NULL : aster_allocate(copy->storage->capacity);\n"
        "    if (source->storage->length != 0U)\n"
        "        memcpy(copy->storage->data, source->storage->data,\n"
        "               source->storage->length);\n"
        "    copy->storage->style_id_count = source->storage->style_id_count;\n"
        "    copy->storage->style_id_capacity =\n"
        "        source->storage->style_id_count;\n"
        "    if (copy->storage->style_id_count != 0U) {\n"
        "        copy->storage->style_ids = aster_allocate(\n"
        "            copy->storage->style_id_count *\n"
        "                sizeof(*copy->storage->style_ids));\n"
        "        memcpy(copy->storage->style_ids, source->storage->style_ids,\n"
        "            copy->storage->style_id_count *\n"
        "                sizeof(*copy->storage->style_ids));\n"
        "    }\n"
        "    copy->storage->style_occurrence_count =\n"
        "        source->storage->style_occurrence_count;\n"
        "    copy->storage->style_occurrence_capacity =\n"
        "        source->storage->style_occurrence_count;\n"
        "    if (copy->storage->style_occurrence_count != 0U) {\n"
        "        copy->storage->style_occurrences = aster_allocate(\n"
        "            copy->storage->style_occurrence_count *\n"
        "                sizeof(*copy->storage->style_occurrences));\n"
        "        memcpy(copy->storage->style_occurrences,\n"
        "            source->storage->style_occurrences,\n"
        "            copy->storage->style_occurrence_count *\n"
        "                sizeof(*copy->storage->style_occurrences));\n"
        "    }\n"
        "    return copy;\n"
        "}\n"
        "void aster_html_drop(aster_html *html) {\n"
        "    if (html == NULL) return;\n"
        "    if (html->attached) {\n"
        "        aster_html_storage *storage = html->storage;\n"
        "        if (storage->child_count == 0U ||\n"
        "            html != &storage->children[storage->child_count - 1U])\n"
        "            aster_trap(\"Html child cleanup order violated\");\n"
        "        *html = (aster_html){0};\n"
        "        --storage->child_count;\n"
        "        return;\n"
        "    }\n"
        "    free(html->storage->data);\n"
        "    free(html->storage->style_ids);\n"
        "    free(html->storage->style_occurrences);\n"
        "    free(html);\n"
        "}\n"
        "bool aster_http_path_matches(aster_str pattern, aster_str path) {\n"
        "    size_t pattern_offset = 0U;\n"
        "    size_t path_offset = 0U;\n"
        "    for (;;) {\n"
        "        while (pattern_offset < pattern.length &&\n"
        "               pattern.data[pattern_offset] == '/') ++pattern_offset;\n"
        "        while (path_offset < path.length &&\n"
        "               path.data[path_offset] == '/') ++path_offset;\n"
        "        size_t pattern_start = pattern_offset;\n"
        "        size_t path_start = path_offset;\n"
        "        while (pattern_offset < pattern.length &&\n"
        "               pattern.data[pattern_offset] != '/' &&\n"
        "               pattern.data[pattern_offset] != '?') ++pattern_offset;\n"
        "        while (path_offset < path.length &&\n"
        "               path.data[path_offset] != '/' &&\n"
        "               path.data[path_offset] != '?') ++path_offset;\n"
        "        size_t pattern_length = pattern_offset - pattern_start;\n"
        "        size_t path_length = path_offset - path_start;\n"
        "        if ((pattern_length == 0U) != (path_length == 0U)) return false;\n"
        "        if (pattern_length == 0U) return true;\n"
        "        if (pattern.data[pattern_start] != ':' &&\n"
        "            (pattern_length != path_length ||\n"
        "             memcmp(pattern.data + pattern_start,\n"
        "                    path.data + path_start, pattern_length) != 0))\n"
        "            return false;\n"
        "    }\n"
        "}\n\n",
        output);
    fputs(
        "aster_str aster_http_path_param(aster_str pattern, aster_str path,\n"
        "                                         aster_str name) {\n"
        "    size_t pattern_offset = 0U;\n"
        "    size_t path_offset = 0U;\n"
        "    aster_str result = {NULL, 0U};\n"
        "    for (;;) {\n"
        "        while (pattern_offset < pattern.length &&\n"
        "               pattern.data[pattern_offset] == '/') ++pattern_offset;\n"
        "        while (path_offset < path.length &&\n"
        "               path.data[path_offset] == '/') ++path_offset;\n"
        "        size_t pattern_start = pattern_offset;\n"
        "        size_t path_start = path_offset;\n"
        "        while (pattern_offset < pattern.length &&\n"
        "               pattern.data[pattern_offset] != '/' &&\n"
        "               pattern.data[pattern_offset] != '?') ++pattern_offset;\n"
        "        while (path_offset < path.length &&\n"
        "               path.data[path_offset] != '/' &&\n"
        "               path.data[path_offset] != '?') ++path_offset;\n"
        "        size_t pattern_length = pattern_offset - pattern_start;\n"
        "        size_t path_length = path_offset - path_start;\n"
        "        if ((pattern_length == 0U) != (path_length == 0U))\n"
        "            return (aster_str){NULL, 0U};\n"
        "        if (pattern_length == 0U) return result;\n"
        "        if (pattern.data[pattern_start] != ':' &&\n"
        "            (pattern_length != path_length ||\n"
        "             memcmp(pattern.data + pattern_start,\n"
        "                    path.data + path_start, pattern_length) != 0))\n"
        "            return (aster_str){NULL, 0U};\n"
        "        if (pattern.data[pattern_start] == ':' &&\n"
        "            pattern_length == name.length + 1U &&\n"
        "            (name.length == 0U ||\n"
        "             memcmp(pattern.data + pattern_start + 1U,\n"
        "                    name.data, name.length) == 0))\n"
        "            result = (aster_str){path.data + path_start, path_length};\n"
        "    }\n"
        "}\n\n",
        output);
    fputs("#endif\n\n", output);
}

bool lang_c_emit_runtime(FILE *output) {
    if (output == NULL) return false;
    c_backend_emit_prelude(output, false);
    c_backend_emit_html_prelude(output, NULL);
    return ferror(output) == 0;
}
